name: ezan_official
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.4
  flutter_svg: ^1.1.0
  hooks_riverpod: ^1.0.4
  font_awesome_flutter: ^10.1.0
  intl: ^0.17.0
  sleek_circular_slider: ^2.0.1
  sliding_up_panel: ^2.0.0+1
  weekday_selector: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
